# -*- coding: utf-8 -*-
"""object_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qhYgEni7i1ndSs6vlwSc53s93CEyad9z
"""

from ultralytics import YOLO
import gradio as gr
from google.colab import files
import matplotlib.pyplot as plt
import cv2

model=YOLO('yolo11n.pt')

#uploaded=files.upload()

#img_path=list(uploaded.keys())[0]

#img=cv2.imread(img_path)

#plt.imshow(img)

#results=model(img_path)

#boxes=results[0].plot()

#plt.imshow(boxes)

def detect_objects(image):
    # Perform inference on the input image
    results = model(image)

    # Display the image with bounding boxes and confidence scores
    # First, extract the image with bounding boxes
    image_with_boxes = results[0].plot()

    return image_with_boxes ## this image (objects detected image) is shown as output

# Create a Gradio interface
iface = gr.Interface(
    fn=detect_objects,    # this function is called when the image is uploaded
    inputs=gr.Image(),         # Input is an image
    outputs=gr.Image(),       # Output is the image with bounding boxes
    live=True                          # Set live to True for instant feedback
)

# Launch the Gradio app
iface.launch()

